# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9.9]
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
              
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run unit tests
        run: |
          echo "::workflow-command parameter1={data},parameter2={data}::{pytest -rf | grep FAILED}"
          
        id: testoutput
        
      - name: send telegram message
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{'155719408'}}
          token: ${{'5099791264:AAEV_ZS2Z9xJnsbBuYrmcLh3AvoseaYvyJ0'}}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Все тесты прошли ОК
            
            Repository: ${{ github.repository }}
            
            
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
      - name: send telegram message
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{'155719408'}}
          token: ${{'5099791264:AAEV_ZS2Z9xJnsbBuYrmcLh3AvoseaYvyJ0'}}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Ошибка в тестах НЕ ОК
            ${{join(steps.testoutput.outputs.*, '\n')}} 
            
            Repository: ${{ github.repository }}
            
            
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
 
 
        

